version: '3.8'

services:
  app:
    build: .
    container_name: orders-management
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
      - elasticsearch
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/ordersdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - .:/app

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
